title: "I Bambini del Circo Massimo"
sentence:
  text: "Il bambino è come un viaggiatore che osserva le cose nuove e cerca di capire il linguaggio sconosciuto di chi lo circonda. Noi adulti siamo i ciceroni di questi viaggiatori che fanno il loro ingresso nella vita umana..."
  author: "Maria Montessori"

owner: "ALESCO SRL"
description: "Asilo Nido I Bambini del Circo Massimo"

alert:
  show: true
  message: Iscrizioni aperte per l'anno scolastico 2018/2019!

social:
    facebook: "https://www.facebook.com/asilonidoromacircomassimo/"
    google-plus: "https://plus.google.com/+ASILONIDOIBambinidelCircoMassimo"

contact:
  address: "Via del Circo Massimo 9, 00153, Roma"
  email: "info@ibambinidelcircomassimo.it"
  phone: "+39 366 1946395"

info:
  opening-hours: "Lun-Ven 7:30 - 18:30"


version: "4"

#url: http://brianmaierjr.github.com/long-haul
baseurl: ""
#paginate_path: "blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
#gems: [jekyll-paginate]
#paginate: 5

navigation:
 - title: Home
   url: /index.html

gems:
 - jekyll-sitemap

exclude:
 - examples

prod-mode: true