title: "I Bambini del Circo Massimo - Asilo Nido Bilingue"


owner: "ALESCO SRL"
description: "Asilo Nido I Bambini del Circo Massimo"

alert:
  show: true
  repeat: true

social:
    facebook: "https://www.facebook.com/asilonidoromacircomassimo/"
    google-plus: "https://plus.google.com/+ASILONIDOIBambinidelCircoMassimo"

contact:
  address: "Via del Circo Massimo 9, 00153, Roma"
  email: "info@ibambinidelcircomassimo.it"
  phone: "+39 366 1946395"

cookie-consent: false

version: "11"

#url: http://brianmaierjr.github.com/long-haul
baseurl: "https://ibambinidelcircomassimo.it"
#paginate_path: "blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
#gems: [jekyll-paginate]
#paginate: 5

navigation:
 - title: Home
   url: /home/

gems:
 - jekyll-sitemap
 - jekyll-multiple-languages-plugin

exclude:
 - examples

languages: ["it", "en"]

prod-mode: true