name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Build
        run: |
          bundle install
          bundle exec jekyll build
