name: Publish Website
on:
  push:
    branches:
    - main
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Build
        run: |
          bundle install
          bundle exec jekyll build

          # fix bug in sitemap generation
          for f in $(find . -name sitemap.xml); do
              sed -i "s/<loc>\//<loc>/" $f
          done

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _site
